app/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/8/23 下午4:04
# @Author  : jlinka
# @File    : __init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_script import Manager
from flask_moment import Moment
import config

bootstrap = Bootstrap()

# mail = Mail()
moment = Moment()


def create_app():
    app = Flask(__name__, static_url_path='/static')
    bootstrap.init_app(app)
    app.config.update(dict(
        SECRET_KEY="powerful secretkey",
        WTF_CSRF_SECRET_KEY="a csrf secret key"))
    return app

app/main/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/8/23 下午6:01
# @Author  : jlinka
# @File    : __init__.py

from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/8/23 下午6:01
# @Author  : jlinka
# @File    : views.py

from . import main
from flask import render_template, redirect, request, url_for, session
from app.form import Search, NewsForm
from app.main.search import searchAll, PaginateLeave, searchCondition, searchWeb, searchOfficialAccounts, findObjectId
from app.main.complex_search import kmeans_search_condition


@main.route('/searchNews', methods=['GET', 'POST'])
def searchNews():
    search = Search()
    newsform = NewsForm()
    session['order'] = ''
    session['source'] = ''  # 清理session
    session['keywords'] = ''  # 清理session，不清理很严重啊，如果有更好的方法请告知，想不到方法保存条件了
    session['web'] = ''
    session['auther'] = ''
    page = int(request.args.get('page')) if request.args.get('page') else 1
    pagination = PaginateLeave(page, searchAll())
    posts = pagination.items
    web = searchWeb()
    officialAccounts = searchOfficialAccounts()
    return render_template('search.html', newsform=newsform, posts=posts, pagination=pagination, search=search,
                           web=web, officialAccounts=officialAccounts, session=session)


@main.route('/search', methods=['GET', 'POST'])
def search():
    newsform = NewsForm()
    search = Search()
    page = int(request.args.get('page')) if request.args.get('page') else 1
    if request.method == 'POST':
        order = request.values.get('order')
        keywords = request.form.get('news')
        source = request.form.getlist('source')
        web = request.form.getlist('web')
        auther = request.form.getlist('auther')
        session['order'] = order
        session['source'] = source
        session['keywords'] = keywords
        session['web'] = web
        session['auther'] = auther
        if order == "智能排序":
            cursor = searchCondition(keywords, source, web, auther, order)
            classifi, xdata = kmeans_search_condition(cursor)
            xdata = sorted(xdata.items(), key=lambda k: k[0])
            return render_template('capacity_search.html', newsform=newsform, classifi=classifi, xdata=xdata,
                                   keywords=keywords,
                                   web=searchWeb(), officialAccounts=searchOfficialAccounts(), session=session)

        if keywords == "" and len(source) == 0:  # 判断搜索条件为空时，显示全部新闻内容
            if web or auther:
                pagination = PaginateLeave(page, searchCondition(keywords, source, web, auther, order))
                posts = pagination.items
                return render_template('search.html', newsform=newsform, posts=posts, pagination=pagination,
                                       keywords=keywords,
                                       web=searchWeb(), officialAccounts=searchOfficialAccounts(), session=session)
            else:
                search = Search()
                newsform = NewsForm()
                session['order'] = ''
                session['source'] = ''  # 清理session
                session['keywords'] = ''  # 清理session，不清理很严重啊，如果有更好的方法请告知，想不到方法保存条件了
                session['web'] = ''
                session['auther'] = ''
                page = int(request.args.get('page')) if request.args.get('page') else 1

                pagination = PaginateLeave(page, searchAll())
                posts = pagination.items
                return render_template('search.html', newsform=newsform, posts=posts, pagination=pagination,
                                       search=search,
                                       web=searchWeb(), officialAccounts=searchOfficialAccounts(), session=session)
        pagination = PaginateLeave(page, searchCondition(keywords, source, web, auther, order))
        posts = pagination.items
        return render_template('search.html', newsform=newsform, posts=posts, pagination=pagination, keywords=keywords,
                               web=searchWeb(), officialAccounts=searchOfficialAccounts(), session=session)

    if request.method == 'GET':
        order = session['order']
        keywords = session['keywords']
        source = session['source']
        web = session['web']
        auther = session['auther']

        if keywords == '' and source == '' and web == '' and auther == '' and order == '':
            pagination = PaginateLeave(page, searchAll())
            posts = pagination.items
            return render_template('search.html', newsform=newsform, posts=posts, pagination=pagination, search=search,
                                   web=searchWeb(), officialAccounts=searchOfficialAccounts(), session=session)
        else:
            pagination = PaginateLeave(page, searchCondition(keywords, source, web, auther, order))
            posts = pagination.items
            return render_template('search.html', newsform=newsform, posts=posts, pagination=pagination,
                                   keywords=keywords,
                                   web=searchWeb(), officialAccounts=searchOfficialAccounts(), session=session)


@main.route('/snapshoot', methods=['GET', 'POST'])
def snapshoot():
    if request.method == 'GET':
        ObjectId = request.args.get('ObjectId')
        news = findObjectId(ObjectId)
        createTime = str(news['createTime'])
        news['createTime'] = "".join(str(createTime[0:4]) + "年" + str(createTime[4:6]) + "月" + str(
            createTime[6:8])) + "日"
        return render_template('snapshoot.html', news=news)

app/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/8/23 下午5:08
# @Author  : jlinka
# @File    : views.py

templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
    <ul class="pagination pagination-lg">
        <p align="center">当前第 {{ pagination.page }} 页 ,共 {{ pagination.total }} 条记录 ,共 {{ pagination.pages }} 页</p>
        <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
            <a href="

                    {% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{% else %}#{% endif %}">
                &laquo;
            </a>
        </li>
        {% for p in pagination.iter_pages() %}
            {% if p %}
                {% if p == pagination.page %}
                    <li class="active">
                        <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="disabled"><a href="#">&hellip;</a></li>
            {% endif %}
        {% endfor %}
        <li {% if not pagination.has_next %} class="disabled"{% endif %}>
            <a href="

                    {% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{% else %}#{% endif %}">
                &raquo;
            </a>
        </li>
    </ul>
{% endmacro %}

templates/addRole.html
{% extends "base.html" %}

{% block title %}添加系统角色{% endblock %}
{% block head %}{{ super() }}{% endblock %}
{% block page_content %}
    <div class="page-header">
        <h1>欢迎您!</h1>
    </div>
    <form method="post">
        {{ form.hidden_tag() }}
        {{ form.roleName.label }}{{ form.roleName(class="form-control",request='') }}
        {{ form.roleDescribe.label }}{{ form.roleDescribe(class="form-control") }}
        <table class="table-bordered">
            <tr>
                <th width="200" height="60">企业信息：</th>
                <th width="200" height="60">学生实习信息：</th>
                <th width="200" height="60">学生实习日志：</th>
                <th width="200" height="60">学生总结与成果：</th>
                <th width="200" height="60">列表：</th>
                <th width="200" height="60">管理：</th>
                <th width="200" height="60">其它：</th>
            </tr>
            <tr>
                <td height="50">
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.COM_INFOR_SEARCH(type='checkbox') }}{{ form.COM_INFOR_SEARCH.label }}
                        </label>
                    </div>
                </td>

                <td>
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.STU_INTERN_SEARCH(type='checkbox') }}{{ form.STU_INTERN_SEARCH.label }}
                        </label>
                    </div>
                </td>
                <td>
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.STU_JOUR_SEARCH(type="checkbox") }}{{ form.STU_JOUR_SEARCH.label }}
                        </label>
                    </div>
                </td>
                <td>
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.STU_SUM_SEARCH(type="checkbox") }}{{ form.STU_SUM_SEARCH.label }}
                        </label>
                    </div>
                </td>
                <td>
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.INTERNCOMPANY_LIST(type="checkbox") }}{{ form.INTERNCOMPANY_LIST.label }}
                        </label>
                    </div>
                </td>
                <td>
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.STU_INTERN_MANAGE(type="checkbox") }}{{ form.STU_INTERN_MANAGE.label }}
                        </label>
                    </div>
                </td>
                                <td>
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.UPLOAD_VISIT(type="checkbox") }}{{ form.UPLOAD_VISIT.label }}
                        </label>
                    </div>
                </td>
            </tr>
            <tr>
                <td height="50">
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.COM_INFOR_EDIT(type="checkbox") }}{{ form.COM_INFOR_EDIT.label }}
                        </label>
                    </div>
                </td>
                <td>
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.STU_INTERN_EDIT(type="checkbox") }}{{ form.STU_INTERN_EDIT.label }}
                        </label>
                    </div>
                </td>
                <td>
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.STU_JOUR_EDIT(type="checkbox") }}{{ form.STU_JOUR_EDIT.label }}
                        </label>
                    </div>
                </td>
                <td>
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.STU_SUM_EDIT(type="checkbox") }}{{ form.STU_SUM_EDIT.label }}
                        </label>
                    </div>
                </td>
                <td>
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.STU_INTERN_LIST(type="checkbox") }}{{ form.STU_INTERN_LIST.label }}
                        </label>
                    </div>
                </td>
                <td>
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.TEA_INFOR_MANAGE(type="checkbox") }}{{ form.TEA_INFOR_MANAGE.label }}
                        </label>
                    </div>
                </td>
            </tr>
            <tr>
                <td height="50">
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.COM_INFOR_CHECK(type="checkbox") }}{{ form.COM_INFOR_CHECK.label }}
                        </label>
                    </div>
                </td>
                <td>
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.STU_INTERN_CHECK(type="checkbox") }}{{ form.STU_INTERN_CHECK.label }}
                        </label>
                    </div>
                </td>
                <td>
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.STU_JOUR_CHECK(type="checkbox") }}{{ form.STU_JOUR_CHECK.label }}
                        </label>
                    </div>
                </td>
                <td>
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.STU_SUM_SCO_CHECK(type="checkbox") }}{{ form.STU_SUM_SCO_CHECK.label }}
                        </label>
                    </div>
                    </div>
                </td>
                <td></td>
                <td>
                    <div class="checkbox-inline">
                        <label style="font-size:12px;">
                            {{ form.PERMIS_MANAGE(type="checkbox") }}{{ form.PERMIS_MANAGE.label }}
                        </label>
                    </div>
                </td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td height="50">
                                        <div class="checkbox-inline">
                        <label style="font-size:12px;">
                                {{ form.SELECT_MANAGE(type="checkbox") }}
                            {{ form.SELECT_MANAGE.label }}
                        </label>
                    </div>
                </td>
            </tr>

        </table>
        <br><br>
        {{ form.submit(class='btn btn-primary') }}
    </form>
    <br><br><br>
{% endblock %}

templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block navbar %}
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">5G舆情搜索系统</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                </ul>

            </div>
        </div>
    </div>
{% endblock %}


{% block head %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge,Chrome=1"/>
    <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon">
    <link rel="icon" href="static/favicon.ico" type="image/x-icon">
    <link href="/static/CSS/bootstrap.min.css" rel="stylesheet">
    <script type="text/javascript" src="/static/JS/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="/static/JS/bootstrap.min.js"></script>
    <style type="text/css">
        .dropdown-submenu {
            position: relative;
        }

        .dropdown-submenu > .dropdown-menu {
            top: 0;
            left: 100%;
            margin-top: -6px;
            margin-left: -1px;
            -webkit-border-radius: 0 6px 6px 6px;
            -moz-border-radius: 0 6px 6px;
            border-radius: 0 6px 6px 6px;
        }

        .dropdown-submenu:hover > .dropdown-menu {
            display: block;
        }

        .dropdown-submenu > a:after {
            display: block;
            content: " ";
            float: right;
            width: 0;
            height: 0;
            border-color: transparent;
            border-style: solid;
            border-width: 5px 0 5px 5px;
            border-left-color: #ccc;
            margin-top: 5px;
            margin-right: -10px;
        }

        .dropdown-submenu:hover > a:after {
            border-left-color: #fff;
        }

        .dropdown-submenu.pull-left {
            float: none;
        }

        .dropdown-submenu.pull-left > .dropdown-menu {
            left: -100%;
            margin-left: 10px;
            -webkit-border-radius: 6px 0 6px 6px;
            -moz-border-radius: 6px 0 6px 6px;
            border-radius: 6px 0 6px 6px;
        }
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

{% endblock %}

templates/capacity_search.html
{#{% extends "base.html" %}#}
{% import "_macros.html"as macros %}

{#{% block title %}5G舆情系统{% endblock %}#}
{% extends "search_mod.html" %}

{% block content %}
    {{ super() }}
    <div class="container">
        <div class="jumbotron">

            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                {#                <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab"#}
                {#                                                          data-toggle="tab">第一类</a>#}
                {#                </li>#}
                {% for i in range(classifi) %}
                    <li role="presentation"><a href="#{{ i }}" aria-controls="{{ i }}" role="tab"
                                               data-toggle="tab">第{{ i }}类</a>
                    </li>
                {% endfor %}
                {#                <li role="presentation"><a href="#messages" aria-controls="messages" role="tab"#}
                {#                                           data-toggle="tab">第三类</a></li>#}
                {#                <li role="presentation"><a href="#settings" aria-controls="settings" role="tab"#}
                {#                                           data-toggle="tab">第四类</a></li>#}
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                {#                <div role="tabpanel" class="tab-pane active" id="home">1</div>#}
                {% for i in xdata %}
                    <div role="tabpanel" class="tab-pane" id="{{ i[0] }}">
                        <form enctype=multipart/form-data>
                            {% for j in i[1] %}
                                <br>
                                <td><h2 class="title">{{ j[0]['title'] }}</h2></td><br>
                                <td>{{ j[0]['createTime'] }}</td>
                                <td>来源：{{ j[0]['source'] }}</td>
                                <td>作者：{{ j[0]['auther'] }}</td>
                                <div class="longtext" style="width: 1000px;">
                                    <td id="content">{{ j[0]['content'] }}</td>
                                </div>
                                {% if j[0]['source'] =="微信公众号" %}
                                    <td><a href="{{ url_for('main.snapshoot', ObjectId =j[0]['_id']) }}">快照</a></td>
                                {% endif %}
                                {% if j[0]['source'] != "微信公众号" %}
                                    <td><a href="{{ j[0]['url'] }}">原文链接</a></td>
                                {% endif %}
                                </tr>
                                <br>
                            {% endfor %}
                        </form>
                    </div>
                {% endfor %}
                {#                <div role="tabpanel" class="tab-pane" id="messages">3</div>#}
                {#                <div role="tabpanel" class="tab-pane" id="settings">4</div>#}
            </div>

        </div>
    </div>
    <script>
        $('#myTabs a').click(function (e) {
            e.preventDefault()
            $(this).tab('show')
        })
    </script>


{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}5G舆情系统{% endblock %}
{% block head %}
{{ super() }}
<style type="text/css">
p{
text-indent: 2em; /*em是相对单位，2em即现在一个字大小的两倍*/
text-align: justify;
font-style: normal;
line-height: 40px;
}

</style>
{% endblock %}<!--先执行父模板-->
{% block content %}
<br>
    <div class="container">
        <div class="jumbotron">
            <h1 align="center">欢迎来到5G舆情系统！</h1>
        </div>
    </div>
    <div class="container">
        <form method="POST" action="{{ url_for('main.searchNews') }}" >
            {{ search.submit(class="btn btn-primary btn-lg btn-block",id='finish',onclick="getLoading()") }}
        </form>
    </div>


{% endblock %}

templates/pagination_show.html
{% macro pagination_show(pagination, endpoint) %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {# 上一页 #}
            <li {% if not pagination.has_prev %}class="disabled"{% endif %}>
                <a href="{% if prev_page %}{{ url_for(endpoint, page=prev_page, **kwargs) }}{% else %}#{% endif %}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>



            {# 下一页 #}
            <li {% if not pagination.has_next %}class="disabled"{% endif %}>
                <a href="{% if next_page %}{{ url_for(endpoint, page=next_page, **kwargs) }}{% else %}#{% endif %}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endmacro %}

templates/search.html
{#{% extends "base.html" %}#}
{% import "_macros.html"as macros %}

{#{% block title %}5G舆情系统{% endblock %}#}
{% extends "search_mod.html" %}

{% block content %}
    {{ super() }}
    <div class="container">
        <div class="jumbotron">

            <td>关键词：{{ session['keywords'] }}</td>
            <td>网站：{{ session['web'] }}</td>
            <td>公众号：{{ session['auther'] }}</td>
            <form enctype=multipart/form-data>
                {% for news in pagination.items %}
                    <br>
                    <td><h2 class="title">{{ news.title }}</h2></td><br>
                    <td>{{ news.createTime }}</td>
                    <td>来源：{{ news.source }}</td>
                    <td>作者：{{ news.auther }}</td>
                    <div class="longtext" style="width: 1000px;">
                        <td id="content">{{ news.content }}</td>
                    </div>
                    {% if news.source =="微信公众号" %}
                        <td><a href="{{ url_for('main.snapshoot', ObjectId =news.ObjectId) }}">快照</a></td>
                    {% endif %}
                    {% if news.source != "微信公众号" %}
                        <td><a href="{{ news.url }}">原文链接</a></td>
                    {% endif %}
                    </tr>
                    <br>
                {% endfor %}
            </form>
            {% if pagination %}
                <div class="pagination">
                    {{ macros.pagination_widget(pagination, 'main.search') }}
                </div>
            {% endif %}
        </div>
    </div>
    </br>
{% endblock %}

templates/search_mod.html
{% extends "base.html" %}
{% block navbar %}
    {{ super() }}
{% endblock %}



{% block head %}
    {{ super() }}
    <style type="text/css">
        p {
            text-indent: 2em; /*em是相对单位，2em即现在一个字大小的两倍*/
            text-align: justify;
            font-style: normal;
            line-height: 40px;
        }

        .longtext {
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: normal;
            display: -webkit-box;
            -webkit-line-clamp: 5;
            -webkit-box-orient: vertical;

        }

        .checkbox-inline {
            width: 220px;
            margin: 0 !important;
        }

        .title {
            float: left;
        {#font-size: 30px;#} width: 60%;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
            color: #666;
            font-weight: 600
        }
    </style>
{% endblock %}
{% block content %}

    <br>
    <div class="container">
        <div class="jumbotron">
            <form method="POST" action="{{ url_for('main.search') }}">
                <div class="input-group">{{ newsform.news(class="form-control") }}
                    <div class="input-group-btn">

                        {{ newsform.submit(class="btn btn-primary",id='finish',onclick="getLoading()") }}<br>
                    </div>
                </div>
                <div style="width:100px;margin:0 auto;text-align:center;padding:10px 0">
                    <a class="btn btn-info" id="filter">
                        筛选
                    </a>
                </div>
                <div class="collapse" id="collapseExample">
                    <!--<label class="checkbox-inline">
                        <input type="checkbox" name="source" value="微信公众号"/>微信公众号
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="source" value="网站"/>网站
                    </label>
                    <br>
            <br>-->
                    <div class="row" id="web">
                        <div class="col-md-2">
                            网站
                            <br/>

                            <label class="checkbox-inline" id="select_web">
                                <input type="checkbox" value=""/>全选
                            </label>
                        </div>
                        <div class="col-md-10">
                            {% for web_b in web %}
                                <label class="checkbox-inline">
                                    <input type="checkbox" name="web" value="{{ web_b }}"/>{{ web_b }}
                                </label>
                            {% endfor %}
                        </div>
                    </div>
                    <br><br><br>
                    <div class="row" id="weixin">
                        <div class="col-md-2">

                            微信公众号
                            <br/>

                            <label class="checkbox-inline" id="select_weixin">
                                <input type="checkbox" value=""/>全选
                            </label>
                        </div>
                        <div class="col-md-10">
                            {% for acc in officialAccounts %}
                                <label class="checkbox-inline">
                                    <input type="checkbox" name="auther" value="{{ acc }}"/>{{ acc }} {#不是我故意拼错的author#}
                                </label>
                            {% endfor %}
                        </div>

                    </div>
                    <div class="col-md-2">

                        搜索模式（默认按照时间排序）

                        <div>
                            <input name="order" value="时间降序" type="radio" checked="checked"> 时间降序
                        </div>
                        <br>
                        <div>
                            <input name="order" value="智能排序" type="radio"> 智能排序(所需时间较长)
                        </div>
                    </div>
                </div>
                <br><br><br>
            </form>
        </div>
    </div>


    <script>
        $(function () {
            $("#select_web").click(function () {

                if ($(this).find('input').is(':checked')) {
                    var web = $("input[name='web']");
                    web.each(function () {
                        $(this).prop('checked', true);
                    });
                } else {
                    var web = $("input[name='web']");
                    web.each(function () {
                        $(this).attr('checked', false);
                    });
                }
            });

            $("#select_weixin").click(function () {

                if ($(this).find('input').is(':checked')) {
                    var web = $("input[name='auther']");
                    web.each(function () {
                        $(this).prop('checked', true);
                    });
                } else {
                    var web = $("input[name='auther']");
                    web.each(function () {
                        $(this).attr('checked', false);
                    });
                }
            });
            $('#filter').click(function () {
                $('.collapse').collapse('toggle')
            })
        });
    </script>
{% endblock %}

templates/snapshoot.html
{% extends "base.html" %}
{% import "_macros.html"as macros %}

{% block title %}5G舆情系统{% endblock %}
{% block head %}
    {{ super() }}


    <style type="text/css">
        p {
            text-indent: 2em; /*em是相对单位，2em即现在一个字大小的两倍*/
            text-align: justify;
            font-style: normal;
            line-height: 40px;
        }

        .longtext {
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: normal;
            display: -webkit-box;
            -webkit-line-clamp: 5;
            -webkit-box-orient: vertical;

        }

        .title {
            float: left;
        {#font-size: 30px;#} width: 60%;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
            color: #666;
            font-weight: 600
        }
    </style>


{% endblock %}<!--先执行父模板-->
{% block content %}
    <br>
    <div class="container">
        {{ news.title }}<br><br>
        {{ news.createTime }}<br><br>
        {{ news.auther }}<br><br>
        {{ news.content }}
    </div>
    </br>
{% endblock %}